using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace FolderRewind.Models
{
    [JsonSerializable(typeof(AppConfig))]
    [JsonSerializable(typeof(BackupConfig))]
    [JsonSerializable(typeof(HistoryRepositoryBinding))]
    [JsonSerializable(typeof(BackupPreset))]
    [JsonSerializable(typeof(BackupPresetDiscoverySource))]
    [JsonSerializable(typeof(BackupPresetShareEnvelope))]
    [JsonSerializable(typeof(TemplatePathRule))]
    [JsonSerializable(typeof(TemplatePathSegment))]
    [JsonSerializable(typeof(TemplatePathMarker))]
    [JsonSerializable(typeof(TemplateShareEnvelope))]
    [JsonSerializable(typeof(RemoteTemplateIndexItem))]
    [JsonSerializable(typeof(RemoteTemplateIndexDocument))]
    [JsonSerializable(typeof(RemoteBackupPresetIndexDocument))]
    [JsonSerializable(typeof(RemoteBackupPresetMatchKey))]
    [JsonSerializable(typeof(GlobalSettings))]
    [JsonSerializable(typeof(BackupSourceScope))]
    [JsonSerializable(typeof(DiscoveryOrigin))]
    [JsonSerializable(typeof(GameDiscoverySettings))]
    [JsonSerializable(typeof(GameLibraryRootSetting))]
    [JsonSerializable(typeof(HotkeySettings))]
    [JsonSerializable(typeof(ArchiveSettings))]
    [JsonSerializable(typeof(AutomationSettings))]
    [JsonSerializable(typeof(AutomationScope))]
    [JsonSerializable(typeof(AutomationConditionType))]
    [JsonSerializable(typeof(ScheduleEntry))]
    [JsonSerializable(typeof(FilterSettings))]
    [JsonSerializable(typeof(BackupFilterMode))]
    [JsonSerializable(typeof(BackupScopeSettings))]
    [JsonSerializable(typeof(FileTypeRule))]
    [JsonSerializable(typeof(CloudSettings))]
    [JsonSerializable(typeof(ConfigCloudHistoryUploadResult))]
    [JsonSerializable(typeof(ManagedFolder))]
    [JsonSerializable(typeof(List<BackupPreset>))]
    [JsonSerializable(typeof(PluginHostSettings))]
    [JsonSerializable(typeof(InstalledPluginInfo))]
    [JsonSerializable(typeof(ConfigKindReference))]
    [JsonSerializable(typeof(ArtifactTransformerReference))]
    [JsonSerializable(typeof(ArtifactTransformPolicySettings))]
    [JsonSerializable(typeof(PersistedArtifactTransformFailureBehavior))]
    [JsonSerializable(typeof(PersistedConsistencyIntent))]
    [JsonSerializable(typeof(ProviderStatePayload))]
    [JsonSerializable(typeof(HostConfigOrigin))]
    [JsonSerializable(typeof(LegacyConfigPreservation))]
    [JsonSerializable(typeof(OperationDiagnosticRecord))]
    [JsonSerializable(typeof(PersistedOperationOutcome))]
    [JsonSerializable(typeof(PersistedDiagnosticSeverity))]
    [JsonSerializable(typeof(PresetProviderDefaults))]
    [JsonSerializable(typeof(Dictionary<string, bool>))]
    [JsonSerializable(typeof(Dictionary<string, string>))]
    [JsonSerializable(typeof(Dictionary<string, JsonElement>))]
    [JsonSerializable(typeof(Dictionary<string, Dictionary<string, string>>))]
    [JsonSerializable(typeof(Dictionary<string, Dictionary<string, JsonElement>>))]
    [JsonSerializable(typeof(Dictionary<string, ProviderStatePayload>))]
    [JsonSerializable(typeof(Dictionary<string, PresetProviderDefaults>))]
    [JsonSourceGenerationOptions(WriteIndented = true)]
    internal partial class AppJsonContext : JsonSerializerContext
    {
    }
}
