using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace FolderRewind.Models
{
    [JsonSerializable(typeof(AppConfig))]
    [JsonSerializable(typeof(BackupConfig))]
    [JsonSerializable(typeof(ConfigTemplate))]
    [JsonSerializable(typeof(TemplatePathRule))]
    [JsonSerializable(typeof(TemplatePathSegment))]
    [JsonSerializable(typeof(TemplatePathMarker))]
    [JsonSerializable(typeof(TemplateShareEnvelope))]
    [JsonSerializable(typeof(RemoteTemplateIndexItem))]
    [JsonSerializable(typeof(RemoteTemplateIndexDocument))]
    [JsonSerializable(typeof(List<RemoteTemplateIndexItem>))]
    [JsonSerializable(typeof(BackupMetadata))]
    [JsonSerializable(typeof(BackupMetadataState))]
    [JsonSerializable(typeof(BackupChangeRecord))]
    [JsonSerializable(typeof(List<BackupChangeRecord>))]
    [JsonSerializable(typeof(FileState))]
    [JsonSerializable(typeof(GlobalSettings))]
    [JsonSerializable(typeof(HotkeySettings))]
    [JsonSerializable(typeof(ArchiveSettings))]
    [JsonSerializable(typeof(AutomationSettings))]
    [JsonSerializable(typeof(AutomationScope))]
    [JsonSerializable(typeof(AutomationConditionType))]
    [JsonSerializable(typeof(ScheduleEntry))]
    [JsonSerializable(typeof(FilterSettings))]
    [JsonSerializable(typeof(BackupFilterMode))]
    [JsonSerializable(typeof(BackupScopeSettings))]
    [JsonSerializable(typeof(FileTypeRule))]
    [JsonSerializable(typeof(CloudSettings))]
    [JsonSerializable(typeof(ConfigCloudHistoryUploadResult))]
    [JsonSerializable(typeof(CloudActiveHistoryManifest))]
    [JsonSerializable(typeof(CloudActiveHistoryEntry))]
    [JsonSerializable(typeof(List<CloudActiveHistoryEntry>))]
    [JsonSerializable(typeof(ManagedFolder))]
    [JsonSerializable(typeof(HistoryItem))]
    [JsonSerializable(typeof(List<HistoryItem>))]
    [JsonSerializable(typeof(List<ConfigTemplate>))]
    [JsonSerializable(typeof(PluginHostSettings))]
    [JsonSerializable(typeof(PluginInstallManifest))]
    [JsonSerializable(typeof(PluginSettingDefinition))]
    [JsonSerializable(typeof(InstalledPluginInfo))]
    [JsonSerializable(typeof(Dictionary<string, bool>))]
    [JsonSerializable(typeof(Dictionary<string, string>))]
    [JsonSerializable(typeof(Dictionary<string, Dictionary<string, string>>))]
    [JsonSourceGenerationOptions(WriteIndented = true)]
    internal partial class AppJsonContext : JsonSerializerContext
    {
    }
}
