name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build App And Plugin
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore Main Project
        run: dotnet restore FolderRewind/FolderRewind.csproj

      - name: Build Main Project
        run: dotnet build FolderRewind/FolderRewind.csproj -c Release -p:Platform=x64 /warnaserror

      - name: Restore Plugin Project
        run: dotnet restore FolderRewind-Plugin-Minecraft/MineRewind/MineRewind.csproj

      - name: Build Plugin Project
        run: dotnet build FolderRewind-Plugin-Minecraft/MineRewind/MineRewind.csproj -c Release -p:Platform=x64 /warnaserror
